### ISSUE TITLE
move the repository to plack organization

### ISSUE THREAD

**Issue by miyagawa** [plack/Plack-Middleware-Session#31]
@stevan could you move the repository to @plack organization using GitHub's admin panel? I can fork and make one, but then we'll lose the redirects. While we're at it, would be nice to normalize the case of the repo i.e. plack/Plack-Middleware-Session. Thanks!

**Comment by stevan** [comment]
I will try and do this some night this week or by the weekend.

**Comment by stevan** [comment]
@miyagawa I can't transfer to the @plack org unless I have admin rights there, would you mind?

**Comment by miyagawa** [comment]
ugh stupid github. invitation sent!

**Comment by stevan** [comment]
Okay, transferred and renamed.

**Comment by miyagawa** [comment]
Thanks!!
