### ISSUE TITLE
inconsistent version

### ISSUE THREAD

**Issue by shoichikaji** [plack/Plack-Middleware-Session#32]
[Plack-Middleware-Session-0.29](http://search.cpan.org/~miyagawa/Plack-Middleware-Session-0.29/) has Plack::Session 0.23.
[Plack-Middleware-Session-0.24](http://search.cpan.org/~miyagawa/Plack-Middleware-Session-0.24/) has Plack::Session 0.24.

Thus if I install Plack::Session, Plack::Middleware::Session is downgraded:
```
$ perl -MPlack::Middleware::Session -le 'print Plack::Middleware::Session->VERSION'
0.29

$ cpanm Plack::Session
--> Working on Plack::Session
Fetching http://www.cpan.org/authors/id/M/MI/MIYAGAWA/Plack-Middleware-Session-0.24.tar.gz ... OK
Configuring Plack-Middleware-Session-0.24 ... OK
Building and testing Plack-Middleware-Session-0.24 ... OK
Successfully installed Plack-Middleware-Session-0.24 (upgraded from 0.23)
1 distribution installed

$ perl -MPlack::Middleware::Session -le 'print Plack::Middleware::Session->VERSION'
0.24
```
I don't think this is intended, so It's nice to bump up versions of all modules in the next release.

**Comment by miyagawa** [comment]
Thanks. Fixed in 0.30.
