### ISSUE TITLE
Session object is not created when using with CGI::Application

### ISSUE THREAD

**Issue by MaxPerl** [plack/Plack-Middleware-Session#34]
Hello dear Plack Team,

Thank you very much for your great work. I tried to use Plack::Middleware::Session with a simple CGI::Application app but I had to create the Plack::Session object in my Application module manually.

I thought - after reading the docs of Plack::Session - this should work:
My instance script:

        my $app = sub {
            my $env = shift;
            my $webapp = AppModule->new( QUERY => CGI::PSGI->new($env),  
	    [bla bla bla]
	    'env' => $env
	    }
	);
	$webapp->run_as_psgi();
        };
        builder {
	    enable 'Session';
	    $app;
        };

My Application Module:

        sub cgiapp_prerun {
	    my $self = shift;
	    my $current_runmode = shift;
	    # initialize the session
	    my $q =$self->query;
	    my $env = $q->env;
	    my $session = $env->{'psgix.session'};
	    # Check the Login Status and if the user is logged in, start the chosen action
	    my $login = $session->get('login');
	    unless ($login) {
		$self->prerun_mode('show_login') if ($current_runmode ne 'login_cb');
	        }
        }

But unfortunately I got the following error:

> Error executing class callback in prerun stage: Can't call method "get" on unblessed reference at /home/maximilian/public_html/cgi-bin/./lib/PLogPSGI.pm line 63. at /home/maximilian/public_html/cgi-bin/extlib/lib/perl5/CGI/Application.pm line 2449

We solved it at the CGI App list with manually creating the session object in cgiapp_prerun as follows:
`
my $session = Plack::Session->new($env);
`

I don't know why the usual way for Plack::Middleware::Session doesn't work. Perhaps you have an idea? It would be great if Plack::Middleware::Session could also under CGI::Application work as usual.

In advance thank you very very much for everything, your invaluable work and your generous help,
Max

**Comment by miyagawa** [comment]
`psgix.session` in $env is just a hash, so that whatever session module of your framework (CGI::Application in this case) can adapt to the interface. You're not supposed to use it directly from your application. Assuming there's no CGI::Application session support for PSGI sessions, the only way you can use this module is directly via Plack::Session, like you do.
